// Env is auto-generated by `npm run cf-typegen` into worker-configuration.d.ts
// ASSETS is provided automatically by Cloudflare when `assets` is set in wrangler.jsonc
declare global {
  interface Env {
    ASSETS: Fetcher;
  }
}

import { handleAuth } from './routes/auth';
import { handleHealth } from './routes/health';
import { handleMenu } from './routes/menu';
import { handleOrders } from './routes/orders';

// Route handlers are tried in order. Each returns a Response or null (not matched).
const routes = [handleHealth, handleAuth, handleMenu, handleOrders];

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith('/api/')) {
      for (const handler of routes) {
        const response = await handler(request, env);
        if (response !== null) return response;
      }
      return Response.json({ error: 'Not found' }, { status: 404 });
    }

    return env.ASSETS.fetch(request);
  },
};
